### ISSUE TITLE
Umbrella issue for version 0.5

### ISSUE THREAD

**Issue by Askir** [kviklet/kviklet#138]
## What's planned for v0.5?

- [x] Reject Requests (see #123), in one way or another allow users to completely reject an execution request.
- [x] LDAP SSO (do you call it that in LDAP?) support (see #122). I have no experience with LDAP so I assume this will be a bit tricky, and I wont add group syncing (yet).
- [x] Test connection Button for Creating new connections
- [x] Simplify multi DB setups for postgres (see #124)
- [x] Finer grained Control on who can and should approve
- [x] Logout button
- [x] Cancel running statements (if they are taking longer than expected or similar)
- [x] Search bar on connections page (not very easy to navigate if you have lots of them)
- [x] MongoDB Connection, this was requested multiple times and I think it makes sense. I don't know yet how much effort it will be though, since of course Mongo wont be able to use the table views, and SQL parsing logic, but I will give it a shot.
- [x] Encryption of DB credentials. This is a personal priority, currently DB user and password are stored in plaintext in the DB, I want to allow to set a sort of "master key" via env variables to make this a tad more secure.
- [x] Filtering of Requests page. Not sure about the details here yet, but some search, pagination, filter by author/state etc. would be nice.
- [x] Same for the Auditlog. (Maybe also an export as file option with your filters?).
- [ ] Option to approve until, or make this the default? Especially since you can now allow running Requests multiple times I think it makes sense to time bound the approvals e.g. for a day/week/month.
- [ ] Maybe a docs page, the readme is becoming rather long... and I think we could use some guides.

____

I thought to keep development a bit more transparent, I'll try keeping my private todo list public for this version.
You're also invited to make suggestions for changes of the list!
But note that while I welcome all suggestions, I reserve the right to have the final say on what I actually implement.

This will always just be a snapshot of my current plans and will change as feature requests and ideas pop up and I discover problems while coding. So it's not a guarantee to be in the next release (unless it's already done).

The timeframe for this release is 1-2 months, so end of July/ start of August 2024.
I will try to keep this cadence in the future, but I'm also looking to start a new job again around September (hi btw if you want to hire me, feel free to shoot me a message 😀). Which means I'll have a little less time to build here (but I will continue!).

**Comment by sapisuper** [comment]
@Askir I think add Logout button is something crucial in web based application. you can consider it. thanks

**Comment by Askir** [comment]
Sure, fair :D

**Comment by sapisuper** [comment]
@Askir if it's something necessary to make configurable export csv compatibility? I think it will prevent data breach or data leak 🤔

**Comment by Askir** [comment]
I am not quite sure what you mean to say. Do you want to be able to turn off CSV downloads?
Security wise it doesn't make an effective difference if the data is downloaded into the users browser and displayed in a table or downloaded as a CSV, in either case the data is in the realm of the users PC so they can store it. Granted the Download as CSV button makes it a bit more convenient, but it doesn't effectively change anything to disable that.

**Comment by sapisuper** [comment]
@Askir 
Do you want to be able to turn off CSV downloads? yes correct. at least is effort to download the data if the button export CSV doesn't exist.

**Comment by Askir** [comment]
Fair I think I can add a config option per connection at least to enable/disable it.

**Comment by Askir** [comment]
@sapisuper logout button is in merged 😄

**Comment by sapisuper** [comment]
@Askir just trying logout button work as well 😃 . Thank you

**Comment by sapisuper** [comment]
Wow just saw the update, currently support MongoDB connection 💯

**Comment by Askir** [comment]
Yes it's not super well tested yet. But running MQL seems to work just fine 😄

**Comment by sapisuper** [comment]
So far simple MQL work well. 

Just wondering Redis Connection also support too ✨

**Comment by sapisuper** [comment]
@Askir I think the logout button should be placed outside the button settings. Or better yet, we should display the name or email of the logged in user and place the logout button next to it.

for I know oidc scopes: openid, email and profile. so I think is possible to display name or email. 

sample display : 
![image](https://github.com/user-attachments/assets/80a4fe9e-b849-4c12-9c47-b4138ccd96ad)

**Comment by Askir** [comment]
I've just published 0.5. There is two features missing from this list, which I hope to get to somewhat soon, but I will also invest some effort into a larger project trying to make Kviklet work a little smoother with the help of websockets as well as help merging the SQL Dump Pull Request.
